name: novacole
description: "Novacole est une plateforme de gestion scolaire innovante, conçue pour transformer la gestion quotidienne des établissements scolaire, de la maternelle au lycée."
publish_to: 'none'
version: 2.2.0+49

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  image_picker: ^1.2.0
  splash_view: ^2.0.1
  font_awesome_flutter: ^10.10.0
  easy_localization: ^3.0.8
  file_picker: ^10.3.2
  multi_select_flutter: ^4.1.3
  jiffy: ^6.4.3
  provider: ^6.1.5+1
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  syncfusion_flutter_calendar: ^30.2.7
  percent_indicator: ^4.2.5
  fluttertoast: ^8.2.12
  loading_animation_widget: ^1.3.0
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.1
  share_plus: ^11.1.0
  flutter_datetime_picker_plus: ^2.2.0
  cached_network_image: ^3.4.1
  circular_countdown_timer: ^0.2.4
  flame_audio: ^2.11.10
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html: ^0.17.0
  image_cropper: ^9.1.0
  dropdown_search: ^6.0.2
  html: ^0.15.6
  easy_date_timeline: ^2.0.9
  timelines_plus: ^1.0.7
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  slugify: ^2.0.0
  open_file: ^3.5.10
  in_app_review: ^2.0.10
  syncfusion_flutter_charts: ^30.2.7
  flutter_image_slideshow: ^0.1.6
  google_fonts: ^6.3.0
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.5
  firebase_analytics: ^12.0.0
  flutter_local_notifications: ^19.4.1
  in_app_update: ^4.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  curved_navigation_bar: ^1.0.6
  uuid: ^4.5.1
  fl_chart: ^1.1.1
  syncfusion_flutter_pdfviewer: ^30.2.7
  flutter_phoenix: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  rename: ^3.1.0
  build_runner: ^2.4.13
  analyzer: ^5.13.0
  hive_generator: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/menus/
    - assets/audio/
    - assets/translations/
